### PR TITLE
[WIP] Build multiple entry-points for client (with parcel) & less transpiling

### LINKED ISSUE #139: Sourcemaps for the cli
The cli does run [`sourceMapSupport.install()`](https://github.com/mdn/stumptown-renderer/blob/7a718c47ed8a6d85d21fe124896a2f556a821ee3/cli/index.js#L31) but I suspect it's not working as expected with babel etc. The cli and its webpack config was the very first thing I started when I started this project so it's most likely rough and hacky. 

The problem comes from the fact that unexpected errors produce near useless stack traces. 

Try...

1. Edit something like `client/src/document.js` and put in a `throw new Error('hello world')` somewhere in some component. 
2. Run `cd cli && CLI_BUILD_HTML=true yarn run run ../stumptown/packaged/html/reference/elements/video.json`

### PR DESCRIPTION
**Pull request by Gregoor**
Fixes #139 
Simplifies #106 

No more sourcemaps required for neither `cli` nor `server` because they aren't transpiled anymore.

`client` is now using `parcel` to build itself both with `index.html` and `app.js` (for `cli` usage) as entry points. It also uses `parcel`'s dev-server. It's almost as little config as `create-react-app`, but I needed to make some changes to some paths. Also apparently `create-react-app` ships with an implementation for `fetch` which isn't part of `jsdom` itself. So that also had to change slightly.

### CODE REVIEW

**Comment by Gregoor** [comment]
Haven't yet found out why the test started timeouting, would look deeper into it when I get a general OK that the direction of this PR is sane

**Comment by Gregoor** [comment]
Oh another todo: I started using `foreman` in `client` to server `index.html` and watch `app.js` simultaneously. Unfortunately that doesn't cascade well, i.e. logs are double timestamped.

**Comment by peterbe** [comment]
What a beast of a PR. Sorry for being slow to review. But I'm not sure I like it yet. It just feels too soon to ditch `react-scripts` for a custom thing. 
It's a near philosophical issue. CRA isn't perfect but it does hide a lot of abstractions. There is great value in avoiding getting what you want exactly some times and I feel like this is one of those times. We might be able to shape up this PR to our hearts content but it does incur a cost in that we're now messing with a train that has momentum. 

I like many things about this PR. I like that sourcemaps are no longer needed in the cli. And some of the configs appear to get simpler for sure. But I don't like that it ditches CRA. 

I'd be more interested in decoupling the cli from the client more. We've talked about the potential idea of making the client near independent from the cli. If we do that, we might be able to move files around so there's 0 imports from `client` from the `cli` and that'd make these two projects a lot more flexible and stable too. 

Also, the `server` isn't important. It's just a thing to help simulate a proper static file server. If you found some east picks to improve it quickly, go ahead. 

My vote is that we focus on https://github.com/mdn/stumptown-renderer/issues/91 first and once the `cli` has been decoupled from `client` we should be able to allow them to individually flourish better. 

What do you think?

**Comment by Gregoor** [comment]
> What a beast of a PR. Sorry for being slow to review. But I'm not sure I like it yet. It just feels too soon to ditch `react-scripts` for a custom thing.

Fair enough! I also just noticed that I threw some refactorings into this that makes this meatier than it needs to be. Will pull those out again, when I touch this again.

> It's a near philosophical issue. CRA isn't perfect but it does hide a lot of abstractions. There is great value in avoiding getting what you want exactly some times and I feel like this is one of those times. We might be able to shape up this PR to our hearts content but it does incur a cost in that we're now messing with a train that has momentum.

I agree that an aversion to this kind of change is right in general, but I'm not sure if I agree in this instance. The only thing that we have to make more explicit/less-hidden compared to CRA is having a babel config. And what it gives us is a faster cli & server with fewer layers.

> My vote is that we focus on #91 first and once the `cli` has been decoupled from `client` we should be able to allow them to individually flourish better.
> 
> What do you think?

I like the idea but I'm rn lacking the vision of what such a `client` would look like and whether it would even still be possible to use CRA in that case. I.e. how would we then build all the content pages?

**Comment by Gregoor** [comment]
maybe worth revisiting in the future but I doubt I'll rebase this one, probably just start anew.

**Pull request closed without merging**
